name: deploy

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    uses: laravel-chronicle/.github/.github/workflows/build.yml
    with:
      image: 'ghcr.io/laravel-chronicle/demo'
      dockerfile: './Dockerfile'
      context: '.'

  cleanup:
    needs: [build-and-push]
    uses: laravel-chronicle/.github/.github/workflows/cleanup.yml
    with:
      package_name: 'demo'
      package_type: 'container'
      min_versions_to_keep: 2

  ssh-and-pull:
    needs: [build-and-push]
    uses: laravel-chronicle/.github/.github/workflows/pull.yml
    with:
      directory: '/home/sites/demo'
